project: 
  type: website
  output-dir: docs/
  render:
  - "*.qmd"

execute:
  freeze: true

website:
  open-graph: true
  page-navigation: true  
  title: "Forest Monitoring Summer School 2026"
  site-url: https://earth-observation-network.github.io/EON2026
  repo-url: https://github.com/earth-observation-network/EON2026
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: textbox
  page-footer: "Earth Observation Network Harz Summer School (2026)" 
  navbar:
    logo: /images/logooil.jpg
  sidebar:
    # logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
      - text: "---"
      - section: "Block 1: Introduction to forest monitoring"
        contents: 
          - block1_magdon/01_TrainingDataCollection.qmd
          - block1_magdon/02_ValidationDataCollection.qmd
      - text: "---"
      - section: "Block 2: Describing and comparing spatial patterns"
        contents: 
          - to_be_defined
      - text: "---"
      - section: "Block 3: Processing of 3D LiDAR data to assess forest structure"
        contents:
          - to_be_defined
          
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-introduction/
          #   text: Basic Readings        
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
          #   text: uav/Flight Planning
      - text: "---"
      - section: "Block 4  Machine learning and validation"
        contents:
          - ml_session/ML_AOA.qmd
        
      - text: "---"
      - section: "Block 5: Measuring and modelling microclimate with mobile climate station"
        contents:
          - mc_session/mc1.qmd
          - mc_session/mc3.qmd
          - mc_session/mc4.qmd
          

format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
